import React from 'react';
import { Check } from 'lucide-react';

const JobPortalBottom = () => {
  const features = [
    {
      text: 'Professional out-of-the-box resumes, instantly generated by the most advanced resume builder technology available.'
    },
    {
      text: 'Effortless crafting. Real-time preview & pre-written resume examples. Dozens of HR-approved resume templates.'
    },
    {
      text: 'Land your dream job with the perfect resume employers are looking for'
    }
  ];

  return (
    <div className="bg-black mt-8 sm:mt-12 lg:mt-16 text-white p-6 sm:p-8 md:p-12 lg:p-16 xl:p-24 rounded-xl sm:rounded-2xl lg:rounded-3xl min-h-[400px] sm:min-h-[450px] lg:min-h-[500px] flex flex-col md:flex-row items-center justify-between gap-8 md:gap-12">
      <div className="w-full md:w-1/2 space-y-6 sm:space-y-8">
        <div className="space-y-2 sm:space-y-4">
          <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold font-poppins leading-tight">
            IMPRESSIVE RESUMES
          </h1>
          <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-poppins font-bold leading-tight">
            EASY ONLINE BUILDER
          </h2>
        </div>
        
        <ul className="space-y-4 hidden sm:block sm:space-y-6">
          {features.map((feature, index) => (
            <li key={index} className="flex items-start space-x-3">
              <Check className="w-5 h-5 sm:w-6 sm:h-6 text-green-500 flex-shrink-0 mt-1" />
              <span className="text-base sm:text-lg text-gray-300 font-poppins">{feature.text}</span>
            </li>
          ))}
        </ul>
        <ul className="space-y-4 sm:hidden sm:space-y-6">
        
            <li className="flex items-start space-x-3">
              <Check className="w-5 h-5 sm:w-6 sm:h-6 text-green-500 flex-shrink-0 mt-1" />
              <span className="text-base sm:text-lg text-gray-300 font-poppins">{features[0].text}</span>
            </li>
    
        </ul>

        <button className="w-full sm:w-auto bg-red-600 hover:bg-red-700 font-poppins text-white font-bold py-3 sm:py-4 px-6 sm:px-8 rounded-full text-base sm:text-lg transition-colors duration-200">
          START MY RESUME
        </button>
      </div>

      <div className="w-full md:w-1/2 flex justify-center md:justify-end">
        <img 
          src="/JobPortalgeekylappy.svg" 
          alt="Job Portal Illustration"
          className="w-full max-w-[300px] sm:max-w-[400px] md:max-w-full h-auto object-contain"
        />
      </div>
    </div>
  );
};

export default JobPortalBottom;